<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * Template Name: Blog
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// The blog page loop logic is located in lib/structure/loops.php.
add_action( 'wp_enqueue_scripts', 'isotope_enqueue_scripts' );
function isotope_enqueue_scripts() {

  wp_enqueue_script('isotope', get_bloginfo('stylesheet_directory') . '/js/blog/jquery.isotope.js', array(

            'jquery'

        )); 

wp_enqueue_script('modernizr', get_bloginfo('stylesheet_directory') . '/js/blog/modernizr.js', array('jquery'));
  wp_enqueue_script('custom', get_bloginfo('stylesheet_directory') . '/js/blog/custom-blog.js', array('jquery'));
  

}

remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop', 'custom_blog_list');

function custom_blog_list(){ ?>

<div class="blog-search">
    <form action="" method="get">
    	<span>Search for: </span><input type="text" name="bsearch">
    	<input type="submit" name="submit" value="submit">
    </form>
</div>	

	<div id="filters" class="button-group">
		<button class="button is-checked" data-filter="*">show all</button>
		<?php $args = array(
            'taxonomy' => 'category'
        );
        $terms = get_terms('category', $args); 
        $count = count($terms);
        $i = 0;
        if ($count > 0) {
            $cape_list = '';
            foreach ($terms as $term) {
            $i++;
            if($term->slug != 'uncategorized'){
            ?>
				<button class="button" data-filter=".<?php echo sprintf($term->slug); ?>"><?php echo $term->name; ?></button>
			<?php 
                }
            }            
        } 
 
        ?>
	</div>

	<div id="grid" class="grid">
	<?php $posts = get_posts(array(
            'post_type' => 'post',
            'posts_per_page' => -1,
            's' => $_GET['bsearch']
        )); ?>
	 
	 <?php 
	 $i = 0;
	 foreach ($posts as $post):
            $my_terms = get_the_terms($post->ID, 'category');
            if ($my_terms && !is_wp_error($my_terms)) {
                $project_slug = array();
                foreach ($my_terms as $term) {
                    $project_slug[] = $term->slug;
                }
            }
            $project_slug_classes = implode(' ', $project_slug);
            $content = $post->post_content;
			$content = strip_tags($content);

            $username = get_userdata( $post->post_author );

			if($i % 4 == 0){
				$first_class = 'first';
			}else{
				$first_class = '';
			}

	?>

        <div class="element-item <?php echo $first_class; ?>  <?php echo $project_slug_classes; ?>" data-category="<?php echo $project_slug_classes; ?>">
			<a href="<?php echo get_permalink($post->ID); ?>"  title="" >
            <?php echo get_the_post_thumbnail($post->ID, array(320, 200)); ?> </a>
           <div class="portfolio_title"><a href="<?php echo get_permalink($post->ID); ?>"  title="" ><h4><?php echo $post->post_title; ?></h4></a></div>
           <div class="portfolio_description"> <?php echo substr($content, 0, 200).'...'; ?>
               <footer>
               By <a href="<?php echo get_author_posts_url( $post->post_author ); ?>"><?php echo $username->display_name; ?></a> on <?php echo get_the_date('F jS, Y',$post->ID); ?>
               </footer>
           </div>
        </div>

    <?php $i++; endforeach; ?>

	</div>
    
        
<?php
    
}

genesis();
